# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               OpenDreamKit
tagline:             'Open Digital Research Environment Toolkit for the Advancement of Mathematics'
description:         'A European Horizon 2020 Research project.'
url:                 http://opendreamkit.org
baseurl:             ''
paginate:            5
paginate_path:       "/news/page:num/"
gems:
  - jemoji

# About/contact
author:
  name:              'The OpenDreamKit consortium'
  url:               http://opendreamkit.org
  email:             contact@opendreamkit.org

# Custom vars
version:             0.1.0
